language: cpp
before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - sudo apt-get install libboost-all-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target package
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T otus2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uromalxr:$BINTRAY_API_KEY "https://api.bintray.com/content/romalxr/otus/lessons/$TRAVIS_BUILD_NUMBER/otus2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"